### PR TITLE
RMS average threshold extensions

### PR DESCRIPTION
**Pull request by cjthomas-opensource**
I've finished testing the "multiple of RMS average" threshold extension; as far as I can tell it's ready to integrate if it looks okay to your team. Other changes:

- Added a checkbox to give a running tattle of the threshold (replacing the input channel's data), for debugging.
- Made the channel selection combobox more descriptive (no more trying to remember what channel #135 was).
- Centralized sampling rate query code (since it's used in several places).
- Fixed a commented-out call to CoreServices::updateSignalChan() (never pass it a null pointer; you'll have a bad time).

There's stubbed-out code (behind "#if TATTLE_ON_NEW_CHANNEL") for putting the threshold tattle on its own channel instead of replacing the input, but that never worked properly (it runs but emits no data). It's based on the code you'd written for the Phase Calculator, so if you see what I did wrong, please do let me know.

### CODE REVIEW

**Comment by ethanbb** [comment]
Hi, is there any urgency that this get merged or are you fine just working off of your branch? I don't think I ought to make the decision to merge it, not being in the lab anymore, but I can try to find some time to test it if that helps.

**Comment by cjthomas-opensource** [comment]
If you'd be willing to take a look at it and then make a recommendation about merging or further changes being needed in the email chain with the lab, that would help a lot; thanks for the response!

**Comment by SumedhNagrale** [comment]
@cjthomas-opensource Take a look at the merged code, I didn't find any conflict. But it would be great if you test it once just to make sure. Let me know if it feasible for you to do it, otherwise I will do the testing sometime next week.

**Comment by cjthomas-opensource** [comment]
Per email, the modified crossing detector is in service with one of our experiment setups. I'll have pilot data in-hand by the end of March, and full-scale datasets will be collected over the following months.

I'm considering adding another change that makes it handle circular inputs (phase) better, but that'll wait until our present experiment is finished, so it'll be on a separate pull request.

**Comment by SumedhNagrale** [comment]
Sounds good! Just ping me on the email, for some reason the notifications don't work the way I am expecting them to.

**Pull request merged**
